name: baseball_quiz_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger: ^1.1.0
  universal_html: ^2.0.8


  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  supabase_flutter: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4

flutter:

  uses-material-design: true

  assets:
    - .env

