name: baseball_quiz_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+7

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  # 選択フォームの作成に使用
  app_tracking_transparency: ^2.0.3
  awesome_select: ^6.0.0
  collection: ^1.16.0
  # 紙吹雪を出すのに使用
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  device_info_plus: ^8.0.0
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^16.2.0
  flutter_riverpod: ^2.1.1
  freezed_annotation: ^2.2.0
  google_fonts: ^3.0.1
  google_mobile_ads: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # 日付を表示用にフォーマットするために使用
  intl: ^0.18.0
  in_app_review: ^2.0.6
  json_annotation: ^4.7.0
  logger: ^1.1.0
  # 現在時刻をネットワークから取得するために使用
  # しばらくメンテされていないという懸念あり
  ntp: ^2.0.0
  package_info_plus: ^3.0.2
  path_provider: ^2.0.11
  pedantic_mono: ^1.20.1
  roggle: ^0.3.0
  share_plus: ^6.3.0
  supabase_flutter: ^1.2.2
  table_calendar: ^3.0.9
  textfield_search: ^0.10.0
  timezone: ^0.9.2
  universal_html: ^2.0.8
  url_launcher: ^6.1.8
  uuid: ^3.0.7
  # アプリversionの比較を容易にするために使用
  version: ^3.0.2

  # Firebase関連
  # アップデートする際、ios/Podfileの「pod 'FirebaseFirestore' ~~」のtagのバージョン上げる必要あるかも
  # アップデートしてエラーが発生したら上記を試してみる
  cloud_firestore: ^4.4.5
  fake_cloud_firestore: ^2.4.1+1
  firebase_analytics: ^10.1.6
  firebase_core: ^2.8.0
  firebase_crashlytics: ^3.0.17
  firebase_messaging: ^14.3.0
  firebase_auth: ^4.3.0

# firebase_authと依存関係のエラーが表示するため、回避策としてoverride
# 参考
# https://github.com/dart-lang/intl/issues/522#issuecomment-1469961807
dependency_overrides:
  # 日付を表示用にフォーマットするために使用
  intl: ^0.18.0

dev_dependencies:
  cider: ^0.1.3
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.1.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  hive_generator: ^2.0.0
  json_serializable: ^6.5.4

flutter_icons:
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/in_app/

flutter_native_splash:
  color: '#FFF8E1'
  image: 'assets/splash/splash.png'
  fullscreen: true
  android_12:
    icon_background_color: '#FFF8E1'
    image: 'assets/splash/splash.png'