// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYxpQ3-jshNQDKzC75DnG9um8QrOTdM2g',
    appId: '1:520205708013:android:02ab787327b43e13937ae4',
    messagingSenderId: '520205708013',
    projectId: 'baseball-quiz-app-prod',
    storageBucket: 'baseball-quiz-app-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6pncPA3MbDBfYcc8NRI-p81vbhXa3KJY',
    appId: '1:520205708013:ios:b26f4f4e627e697f937ae4',
    messagingSenderId: '520205708013',
    projectId: 'baseball-quiz-app-prod',
    storageBucket: 'baseball-quiz-app-prod.appspot.com',
    iosClientId:
        '520205708013-60qqj0946mpt9ktufc33km3ajnfdnhih.apps.googleusercontent.com',
    iosBundleId: 'com.toda.baseballQuizApp.prod',
  );
}
