targets:
  $default:
    builders:
      auto_route_generator:
        generate_for:
          include:
            - lib/ui/page/*.dart
            - lib/core/router/*.dart
      freezed:
        generate_for:
          include:
            - "lib/ui/controller/*.dart"
      riverpod_generator:
        generate_for:
          include:
            - "lib/ui/controller/*.dart"
            - "lib/ui/controller/**/*.dart"
            - "lib/core/router/*.dart"