name: check

on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 空の.envを作成
      # 必要あれば、githubのSECRET情報から値を取得して.envに書き込む
      # 参考
      # https://zenn.dev/big_tanukiudon/articles/fc1a2ff562ce3d#2.-github-actions-%E3%81%AEstep%E3%82%BB%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%A7.env%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E4%BD%9C%E6%88%90%E3%81%99%E3%82%8B
      - name: Create dot env file
        shell: bash
        run: |
          touch package/app/.env

      - name: Setup Flutter
        id: setup-flutter
        uses: ./.github/actions/setup_flutter

      - name: Run flutter version
        run: flutter --version

      - name: Prepare Melos
        run: echo "MELOS_SDK_PATH=${{ steps.setup-flutter.outputs.flutter-path }}" >> "$GITHUB_ENV"

      - name: Install Melos
        uses: bluefireteam/melos-action@v3

      - name: Run melos bs
        run: melos bs

      - name: Install matcher
        run: echo "::add-matcher::.github/analyzer-problem-matcher.json"

      - name: Run melos analyze
        shell: bash
        run: |
          melos analyze | tee ./flutter_analyze_report.txt

      - name: Remove matcher
        if: always()
        run: echo "::remove-matcher owner=dart-analyzer::"

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        if: always()
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Danger
        uses: MeilCli/danger-action@v5
        if: always()
        with:
          plugins_file: 'Gemfile'
          install_path: 'vendor/bundle'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 空の.envを作成
      # 必要あれば、githubのSECRET情報から値を取得して.envに書き込む
      # 参考
      # https://zenn.dev/big_tanukiudon/articles/fc1a2ff562ce3d#2.-github-actions-%E3%81%AEstep%E3%82%BB%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%A7.env%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E4%BD%9C%E6%88%90%E3%81%99%E3%82%8B
      - name: Create dot env file
        shell: bash
        run: |
          touch package/app/.env

      - name: Setup Flutter
        id: setup-flutter
        uses: ./.github/actions/setup_flutter

      - name: Run flutter version
        run: flutter --version

      - name: Prepare Melos
        run: echo "MELOS_SDK_PATH=${{ steps.setup-flutter.outputs.flutter-path }}" >> "$GITHUB_ENV"

      - name: Install Melos
        uses: bluefireteam/melos-action@v3

      - name: Run melos bs
        run: melos bs

      - name: Run melos test
        run: melos test --no-select